--DROP TABLE USER_INFO;
--DROP TABLE ORG_INFO;
--DROP TABLE PAPERS_TYPE;
--DROP TABLE PICTURE_INFO;

CREATE TABLE IF NOT EXISTS USER_INFO(
	USER_ID VARCHAR(32) NOT NULL COMMENT '用户编号',
	USER_NAME VARCHAR(50) NOT NULL COMMENT '用户名称',
	PASSWORD VARCHAR(80) NOT NULL COMMENT '用户密码',
	ORG_NO VARCHAR(20) DEFAULT NULL COMMENT '机构编号',
	BRANCH_NO VARCHAR(20) DEFAULT NULL COMMENT '下属机构号',
	REMARK VARCHAR(50) DEFAULT NULL COMMENT '备注',
	CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
	UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY(USER_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT '用户信息表';

CREATE TABLE IF NOT EXISTS ORG_INFO(
	ORG_NO VARCHAR(20) NOT NULL COMMENT '机构编号',
	BRANCH_NO VARCHAR(20) DEFAULT NULL COMMENT '下属机构号',
  	SUPER_NO VARCHAR(20) DEFAULT NULL COMMENT '上级机构号',
  	BRANCH_CLASS VARCHAR(20) DEFAULT NULL COMMENT '下属机构类别',
  	BRANCH_PHONE VARCHAR(20) DEFAULT NULL COMMENT '下属机构联系电话',
  	BRANCH_CITY VARCHAR(100) DEFAULT NULL COMMENT '下属机构所在城市',
  	BRANCH_ADDR VARCHAR(100) DEFAULT NULL COMMENT '下属机构详细地址',
  	BRANCH_DISC VARCHAR(100) DEFAULT NULL COMMENT '下属机构描述',
  	TREE_ID BIGINT(20) DEFAULT NULL COMMENT '树节点（排序）',
  	TREE_PID BIGINT(20) DEFAULT NULL COMMENT '树父节点（排序）',
  	CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  	UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  	PRIMARY KEY(ORG_NO)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT '机构信息表';


CREATE TABLE IF NOT EXISTS PAPERS_TYPE(
	ITEM_CODE VARCHAR(20) NOT NULL COMMENT '类型码',
	ITEM_VALUE VARCHAR(200) NOT NULL COMMENT '类型名称',
	ORG_NO VARCHAR(20) DEFAULT NULL COMMENT '机构编号',
	BRANCH_ID VARCHAR(20) DEFAULT NULL COMMENT '下属机构号',
	SYS_NO VARCHAR(20) NOT NULL COMMENT '系统编号',
	SYS_NAME VARCHAR(50) NOT NULL COMMENT '系统名称',
	SORT_NO VARCHAR(20) COMMENT '排序号',
	GRADE INT(11) COMMENT '级别',
	STATUS CHAR(1) DEFAULT '1' COMMENT '是否生效（0 无效， 1 有效）',
	PRIMARY KEY(ITEM_CODE, SYS_NO)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT '图片类型表';


CREATE TABLE IF NOT EXISTS PICTURE_INFO(
  PIC_ID VARCHAR(32) NOT NULL COMMENT '图片编号',
  APP_NO VARCHAR(20) DEFAULT NULL COMMENT '服务系统进件号',
  IMG_NAME VARCHAR(80) DEFAULT NULL COMMENT '文件名称',
  SAVE_NAME VARCHAR(80) DEFAULT NULL COMMENT '保存文件名称',
  PAPER_TYPE VARCHAR(100) DEFAULT NULL COMMENT '具体类型如：身份证件、工资证明、房产证明',
  SYS_NO VARCHAR(20) NOT NULL COMMENT '系统编号',
  SYS_NAME VARCHAR(20) DEFAULT NULL COMMENT '系统名称',
  ID_NO VARCHAR(100) DEFAULT NULL COMMENT '证件编号',
  ID_TPYE VARCHAR(100) DEFAULT NULL COMMENT '证件类型',
  K_ID VARCHAR(32) DEFAULT NULL COMMENT '文件管理系统唯一标识[FDFS]',
  PIC_FLAG VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '新接口文件标识（1 新接口， 0 老接口）',
  ORG_NO VARCHAR(20) DEFAULT NULL COMMENT '机构编号',
  BRANCH_ID VARCHAR(20) DEFAULT NULL COMMENT '下属机构编号',
  IS_PATCH_BOLT VARCHAR(4) DEFAULT NULL COMMENT '是否补件（Y 是  N 否）',
  IS_WASTE VARCHAR(20) DEFAULT NULL COMMENT '是否失效（Y 是  N 否）',
  IS_SMALL VARCHAR(1) DEFAULT NULL COMMENT '是否缩略图（Y 是  N 否）',
  SORT_NO BIGINT(20) DEFAULT NULL COMMENT '排序号',
  REMARK VARCHAR(200) DEFAULT NULL COMMENT '备注',
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (PIC_ID),
  KEY IDX_APP_NOSUBCLASS_SORT (APP_NO, PAPER_TYPE),
  KEY IDX_SAVENAME (SAVE_NAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT '图片信息表';